spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/hairsalonlu?serverTimezone=UTC"
    username: "root"
    password: "root"
  jpa:
    hibernate.ddl-auto: "update"

javafx:
  title: Lulu Nails TPV
  stage:
    resizable: true
  main:
    tree: true
    toolbar: true
  appicons:
    - /images/luluNails_64x64.png
    - /images/luluNails_46x46.png
    - /images/luluNails_36x36.png
    - /images/luluNails_24x24.png
    - /images/luluNails_16x16.png

flyway:
  enabled: true
    
logging:
  level:
    com.skynet: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

company:
  iva: 0.1
  name: LuluNails
  address: Av. Marqués de Figueroa 55 bajo derecha, B
  zip: 15500, Fene
  phone: 722 758 395
  email: Luluivnails@gmail.com